CREATE TABLE topico(
id bigint NOT NULL AUTO_INCREMENT,
titulo VARCHAR(25) NOT NULL,
mensaje VARCHAR(200) NOT NULL,
fecha_Creacion DATETIME NOT NULL,
estado ENUM('ABIERTO', 'CERRADO') NOT NULL,
autor VARCHAR(50) NOT NULL,
curso ENUM(
'JAVA',
'SPRING',
'JAVASCRIPT',
'LOGICA_DE_PROGRAMACION',
'BASE_DE_DATOS',
'SOFT_SKILLS') NOT NULL,
respuestas VARCHAR(200) NOT NULL,
PRIMARY KEY (id)
);